<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Setting up reports and test is ready ]]>
    </line>
    <line>
      <![CDATA[Settings Done ]]>
    </line>
    <line>
      <![CDATA[SS for Failure ]]>
    </line>
    <line>
      <![CDATA[SS Failure method done ]]>
    </line>
    <line>
      <![CDATA[SS for Failure ]]>
    </line>
    <line>
      <![CDATA[SS Failure method done ]]>
    </line>
  </reporter-output>
  <suite started-at="2022-01-22T22:30:51 IST" name="Default suite" finished-at="2022-01-22T22:31:46 IST" duration-ms="54308">
    <groups>
    </groups>
    <test started-at="2022-01-22T22:30:51 IST" name="Default test" finished-at="2022-01-22T22:31:46 IST" duration-ms="54308">
      <class name="com.automation.testcases.TC_LoginPag_01">
        <test-method is-config="true" signature="setupSuite()[pri:0, instance:com.automation.testcases.TC_LoginPag_01@2ed2d9cb]" started-at="2022-01-22T22:30:50 IST" name="setupSuite" finished-at="2022-01-22T22:30:51 IST" duration-ms="1414" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Setting up reports and test is ready ]]>
            </line>
            <line>
              <![CDATA[Settings Done ]]>
            </line>
          </reporter-output>
        </test-method> <!-- setupSuite -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.automation.testcases.TC_LoginPag_01@2ed2d9cb]" started-at="2022-01-22T22:30:51 IST" name="setup" finished-at="2022-01-22T22:31:30 IST" duration-ms="38978" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="LPValidation()[pri:1, instance:com.automation.testcases.TC_LoginPag_01@2ed2d9cb]" started-at="2022-01-22T22:31:30 IST" name="LPValidation" finished-at="2022-01-22T22:31:39 IST" duration-ms="8513" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LPValidation -->
        <test-method is-config="true" signature="ssOnFailure(org.testng.ITestResult)[pri:0, instance:com.automation.testcases.TC_LoginPag_01@2ed2d9cb]" started-at="2022-01-22T22:31:39 IST" name="ssOnFailure" finished-at="2022-01-22T22:31:42 IST" duration-ms="3053" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=LPValidation status=SUCCESS method=TC_LoginPag_01.LPValidation()[pri:1, instance:com.automation.testcases.TC_LoginPag_01@2ed2d9cb] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[SS for Failure ]]>
            </line>
            <line>
              <![CDATA[SS Failure method done ]]>
            </line>
          </reporter-output>
        </test-method> <!-- ssOnFailure -->
        <test-method signature="validateTitle()[pri:0, instance:com.automation.testcases.TC_LoginPag_01@2ed2d9cb]" started-at="2022-01-22T22:31:42 IST" name="validateTitle" finished-at="2022-01-22T22:31:42 IST" depends-on-methods="com.automation.testcases.TC_LoginPag_01.LPValidation" duration-ms="303" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [GTPL Bank Home Page !] but found [GTPL Bank Manager HomePage]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [GTPL Bank Home Page !] but found [GTPL Bank Manager HomePage]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.automation.testcases.TC_LoginPag_01.validateTitle(TC_LoginPag_01.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitle -->
        <test-method is-config="true" signature="ssOnFailure(org.testng.ITestResult)[pri:0, instance:com.automation.testcases.TC_LoginPag_01@2ed2d9cb]" started-at="2022-01-22T22:31:42 IST" name="ssOnFailure" finished-at="2022-01-22T22:31:45 IST" duration-ms="2749" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validateTitle status=FAILURE method=TC_LoginPag_01.validateTitle()[pri:0, instance:com.automation.testcases.TC_LoginPag_01@2ed2d9cb] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[SS for Failure ]]>
            </line>
            <line>
              <![CDATA[SS Failure method done ]]>
            </line>
          </reporter-output>
        </test-method> <!-- ssOnFailure -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.automation.testcases.TC_LoginPag_01@2ed2d9cb]" started-at="2022-01-22T22:31:45 IST" name="teardown" finished-at="2022-01-22T22:31:46 IST" duration-ms="497" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.automation.testcases.TC_LoginPag_01 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
